### ISSUE TITLE
An error occurred while accessing a deceased individual while not logged in

### ISSUE THREAD

**Issue by iyoua** [vytux-com/vytux_cousins#18] opened 2022-05-25 14:39 UTC
```
Call to a member function attribute() on null …/modules_v4/vytux_cousins-master/module.php:217
#0 …/modules_v4/vytux_cousins-master/resources/views/tab.phtml(26): Vytux\WebtreesModules\VytuxCousins\VytuxCousinsTabModule->getChildLabel()
#1 …/app/View.php(183): include('/www/wwwroot/ch...')
#2 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#3 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#4 …/modules_v4/vytux_cousins-master/module.php(248): view()
...

**Comment by vytux-com** [comment] 2022-05-25 21:42
Are you able to provide the raw gedcom record for this? 

At a guess it's probably caused by an individual with no family records? I'll have a look tonight, but it would be good to have some reproducible records so I can test the fix

**Comment by jpretired** [comment] 2022-05-26 08:50
I am experiencing the same issue.
The raw gedcom record is:

0 @I157@ INDI
1 NAME Vendelín /Prause/
2 GIVN Vendelín
2 SURN Prause
1 SEX M
1 BIRT
2 DATE 4 APR 1912
2 PLAC Nový Hrádek-Rzy, Královéhradecký, Česko
1 DEAT
2 DATE 5 MAY 1912
2 PLAC Nový Hrádek-Rzy, Královéhradecký, Česko
1 FAMC @F178@

**Comment by iyoua** [comment] 2022-05-26 08:51
When viewing a deceased individual without logging in, an error will occur when the person has a cousin, and no error will occur if he does not have a cousin. After logging in, it will display normal.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vytux-com/vytux_cousins"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 凌晨5:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vytux-com/vytux_cousins] An error occurred while accessing a deceased individual while not logged in (Issue #18)





 
Are you able to provide the raw gedcom record for this?
 
At a guess it's probably caused by an individual with no family records? I'll have a look tonight, but it would be good to have some reproducible records so I can test the fix

**Comment by iyoua** [comment] 2022-05-26 09:12
You can test it at the following website:
https://chen.zong.pub/tree/my/individual/X65/chen-pi-hao
account number:test
password:test1234

**Comment by vytux-com** [comment] 2022-05-26 10:42
OK, found the issue and fix is about to be committed, its caused by privacy when some relatives are private and thus the family record gets hidden by webtrees.

**Closed as completed** 2022-05-26 10:43 UTC
